/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#cacbcb",
        "primary-container": "#ffc107",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c8c6c5",
        "surface-variant": "#353535",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary": "#e7e7e7",
        "surface-container-lowest": "#0e0e0e",
        "error": "#ffb4ab",
        "background": "#131313",
        "on-tertiary-container": "#545656",
        "surface-container": "#202020",
        "primary-fixed-dim": "#fabd00",
        "outline-variant": "#4f4632",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-highest": "#353535",
        "tertiary-fixed": "#e2e2e2",
        "surface-tint": "#fabd00",
        "secondary-fixed": "#e5e2e1",
        "error-container": "#93000a",
        "inverse-primary": "#785900",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "on-primary": "#3f2e00",
        "on-error": "#690005",
        "primary-fixed": "#ffdf9e",
        "on-secondary-fixed-variant": "#474646",
        "on-secondary-fixed": "#1c1b1b",
        "primary": "#ffe4af",
        "surface-container-low": "#1b1b1c",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-container": "#bab8b7",
        "on-primary-container": "#6d5100",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#5b4300",
        "surface": "#131313",
        "inverse-on-surface": "#303030",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#4a4949",
        "on-primary-fixed": "#261a00",
        "on-secondary": "#313030",
        "outline": "#9c8f78",
        "on-tertiary": "#2f3131",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#d4c5ab"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "80px",
        "margin-mobile": "16px",
        "md": "24px",
        "xs": "8px",
        "sm": "16px",
        "lg": "40px",
        "gutter": "24px",
        "max-width": "1280px",
        "base": "4px"
      },
      "fontFamily": {
        "headline-md": ["Montserrat"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "price-display": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "display-lg-mobile": ["Montserrat"],
        "label-bold": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "price-display": ["20px", {"lineHeight": "1.0", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-bold": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
