/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "background": "#faf9fe",
        "on-surface": "#1a1b1f",
        "on-secondary-fixed-variant": "#474746",
        "surface-bright": "#faf9fe",
        "secondary": "#5f5e5e",
        "surface-container": "#eeedf3",
        "on-secondary-fixed": "#1c1b1b",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-variant": "#e3e2e7",
        "on-secondary-container": "#636262",
        "inverse-primary": "#b4d339",
        "surface-container-low": "#f4f3f8",
        "on-primary-fixed": "#171e00",
        "inverse-surface": "#2f3034",
        "primary-fixed-dim": "#b4d339",
        "primary-container": "#c7e74c",
        "on-tertiary-container": "#5d5f5c",
        "primary": "#536500",
        "on-tertiary-fixed-variant": "#454744",
        "on-surface-variant": "#454936",
        "tertiary-container": "#d9dad5",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0f5",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c9b0",
        "surface": "#faf9fe",
        "surface-container-high": "#e9e7ed",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "outline": "#767964",
        "surface-tint": "#536500",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3e4c00",
        "surface-dim": "#dad9df",
        "on-primary": "#ffffff",
        "tertiary": "#5d5f5b",
        "secondary-container": "#e2dfde",
        "tertiary-fixed": "#e2e3de",
        "tertiary-fixed-dim": "#c6c7c2",
        "surface-container-highest": "#e3e2e7",
        "primary-fixed": "#d0f054",
        "on-primary-container": "#546600",
        "on-background": "#1a1b1f",
        "on-tertiary-fixed": "#1a1c19"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter-grid": "1rem",
        "stack-sm": "0.5rem",
        "margin-page": "1.25rem",
        "stack-md": "1rem",
        "stack-lg": "1.5rem"
      },
      "fontFamily": {
        "price-display": ["Geist"],
        "body-md": ["Inter"],
        "headline-sm": ["Geist"],
        "label-lg": ["Geist"],
        "headline-xl": ["Geist"],
        "headline-lg": ["Geist"],
        "body-sm": ["Inter"],
        "label-md": ["Geist"]
      },
      "fontSize": {
        "price-display": ["20px", {"lineHeight": "24px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm-mobile": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-lg": ["14px", {"lineHeight": "18px", "fontWeight": "600"}],
        "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    }
  },
  plugins: [],
}
